{{- if and .Values.pvc.enabled (not .Values.pvc.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.pvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
{{- with .Values.pvc.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "wordpress.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
{{- if .Values.pvc.storageClass }}
{{- if (eq "-" .Values.pvc.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.pvc.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
