apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  host: {{ .Values.wordpressDbHost | b64enc }}
  dbname: {{ .Values.wordpressDbName | b64enc }}
  user: {{ .Values.wordpressDbUser | b64enc }}
  password: {{ .Values.wordpressDbPassword | b64enc }}
  rootpassword: {{ .Values.mysqlRootPassword | b64enc }}

